#!/usr/bin/env bash
# Checks DNS records for passed domain and subdomain

domain="$1"
subdomain="$2"

if [ "$domain" == "" ]
then
	echo "USAGE: domain subdomain"
	exit 1;
fi

if [ "$subdomain" != "" ]
then
	subdomain="$subdomain."
else
	subdomains=("www", "lb-01", "web-01", "web-02")
fi

needed_fields=$(dig "$subdomain$domain" | grep -A1 "ANSWER SECTION:" | awk 'NR==2 {print $4, $5}')

if [ "$needed_fields" == "" ]
then
	exit 1;
fi

record_type=$(echo $needed_fields | cut -d ' ' -f 1)
ip_address=$(echo $needed_fields | cut -d ' ' -f 2)

