#!/usr/bin/env bash
# Installs and configures an nginx web server

# Install and set-up nginx
sudo apt-get update && \
sudo apt-get -y install nginx ufw && \
sudo ufw allow 'Nginx HTTP'

# change the default response
echo 'Hello World!' | sudo tee /var/www/html/index.html

# Restart nginx
sudo service nginx start
