#!/usr/bin/env bash
# Installs and configures an nginx web server

# Install and set-up nginx
sudo apt-get update && \
sudo apt-get -y install nginx ufw && \
sudo ufw allow 'Nginx HTTP'

# change the default response
sudo mv /var/www/html/index.html /var/www/html/index-backup.html
sudo echo 'Hello World!' > /var/www/html/index.html

# Restart nginx
pkill nginx
nginx