#!/usr/bin/env bash
# Installs and configures an nginx web server

# Install and set-up nginx
sudo apt-get update && \
sudo apt-get -y install nginx ufw && \
sudo ufw allow 'Nginx HTTP'

# change the default response
echo 'Hello World!' | sudo tee /var/www/html/index.html

# setup redirect
replacement_string="server_name _;\n\n\tlocation \/redirect_me {\n\t\treturn 301 https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4;\n\t}\n"
sudo sed -i "s/server_name _;/$replacement_string/" /etc/nginx/sites-enabled/default

# Restart nginx
sudo service nginx restart
