#!/usr/bin/env bash
# Installs and configures an nginx web server

# Install and set-up nginx
sudo apt-get update && \
sudo apt-get -y install nginx ufw && \
sudo ufw allow 'Nginx HTTP'

# change the default response
echo 'Hello World!' | sudo tee /var/www/html/index.html

# setup redirect
replacement_string="server_name _;\n\n\tlocation \/redirect_me {\n\t\treturn 301 https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4;\n\t}\n"
sudo sed -i "s/server_name _;/$replacement_string/" /etc/nginx/sites-enabled/default

# setup 404
error_replacement_string="server_name _;\n\n\terror_page 404 \/custom_404.html;\n\tlocation = \/custom_404.html {\n\t\troot \/usr\/share\/nginx\/html;\n\t\tinternal;\n\t}"
sudo sed -i "s/server_name _;/$error_replacement_string/" /etc/nginx/sites-enabled/default

echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/custom_404.html

# Setup headers

host_name=$(hostname)
search_text="listen \[\:\:\]\:80 default_server;"
replacement_text="$search_text\n\n\tadd_header X-Served-By $host_name;\n"
sudo sed -i "s/$search_text/$replacement_text/" /etc/nginx/sites-enabled/default
sudo service nginx restart#!/usr/bin/env bash

# Restart nginx
sudo service nginx restart
