#!/usr/bin/env bash
# Pings an IP address 5 times

FIRST_ARGUMENT="$1"

if [ -z "$FIRST_ARGUMENT" ]; then
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}";
    exit 1
fi

ping -c 5 "$FIRST_ARGUMENT"
