#!/usr/bin/env bash
# - Creates the file /var/run/myscript.pid containing its PID
# - Displays To infinity and beyond indefinitely
# - Displays I hate the kill command when receiving a SIGTERM signal
# - Displays Y U no love me?! when receiving a SIGINT signal
# - Deletes the file /var/run/myscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal


FILE="/var/run/myscript.pid"

touch "$FILE" && echo "$$" > "$FILE"

handleSigterm() {
  echo "I hate the kill command";
}

handleSigint() {
  echo "Y U no love me?!";
}

cleanUp() {
  rm "$FILE"
  exit
}

trap handleSigterm SIGTERM
trap handleSigint SIGINT
trap cleanUp SIGQUIT SIGTERM

while true; do 
  echo "To infinity and beyond"
  sleep 2
done
