#!/usr/bin/env bash
# - Displays 'To infinity and beyond' indefinitely, with a 'sleep 2' between each iteration
# - Prints 'I am invincible!!!' when it receives a SIGTERM signal


ignoreSignal() {
  echo "I am invincible!!!"
}

trap ignoreSignal SIGTERM

while true; do
  echo "To infinity and beyond"
  sleep 2;
done
