#!/usr/bin/env bash
# Displays Best School 10 times but for 9th iteration, also displays Hi after

n=1

while [ $n -lt 11 ]; do
	echo "Best School";

	if [ $n -eq 9 ]; then
		echo "Hi"
	fi
	
	n=$((n + 1))
done
