#!/usr/bin/env bash
# Displays numbers 1 to 20 and:
#	After displaying 4, also displays "bad luck from China"
#	After displaying 9, also displays "bad luck from Japan"
#	After displaying 17, also displays "bad luck from Italy"

BLF="bad luck from"
n=1

while [ $n -le 20 ]; do
	echo "$n"

	case $n in
		4)
			echo "$BLF China"
			;;
		9)
			echo "$BLF Japan"
			;;
		17)
			echo "$BLF Italy"
			;;
	esac

	n=$((n + 1));
done
