#!/usr/bin/env bash
# Displays the time for 12 hours and 59 minutes:
#	Displays hours 0 to 12
# 	Displays minutes from 1 to 59
# Requirements:
#	You must use the while loop (for and until are forbidden)

HOURS=0

while [ $HOURS -le 12 ]; do
	echo "Hour: $HOURS"
	MINUTES=1 

	while [ $MINUTES -le 59 ]; do
		echo "$MINUTES"
		MINUTES=$((MINUTES + 1));
	done

	HOURS=$((HOURS + 1));
done
