#!/usr/bin/env bash
# Displasy the content of current directory in a list format
# where only the part of the name after the first dash is displayed

FILES=$(ls)

for file in $FILES; do  
  echo "$file" | cut -d '-' -f2;
done
