#!/usr/bin/env bash
# Displasy the content of current directory in a list format
# where only the part of the name after the first dash is displayed

for file in ./*; do
  
  if [ "$file" != ".*" ]; then
    echo "$file" | cut -d '-' -f2;
  fi

done
