#!/usr/bin/env bash
# Make localhost resolve to 127.0.0.2
# Make facebook.com resolve to 8.8.8.8

echo "127.0.0.2  localhost" | sudo tee /etc/hosts > /dev/null
echo "8.8.8.8  facebook.com" | sudo tee -a /etc/hosts > /dev/null

